service: ${file(./config.json):service_id}

provider:
  name: google
  runtime: nodejs
  memorySize: 256
  timeout: 60s
  project: ${file(./config.json):project_id}
  credentials: ${file(./config.json):credentials_file}

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - config.json.sample
    - LICENSE
    - README.md

functions:
  ping:
    handler: ping
    events:
      - http: path

  check:
    handler: check
    events:
      - http: path

  contact:
    handler: contact
    events:
      - http: path

frameworkVersion: "=1.25.0"
